apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-preview
spec:
  generators:
    - pullRequest:
        github:
          owner: LapoElisacci 
          repo: k8s-preview
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 30
  template:
    metadata:
      name: 'k8s-preview-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'preview-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: .
        repoURL: 'https://github.com/lapoelisacci/k8s-preview-argocd.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'preview-{{branch}}'
            - name: version
              value: '{{head_sha}}'
            - name: image
              value: k8s-preview
            - name: name
              value: k8s-preview
      syncPolicy:
        automated:
          selfHeal: true
